# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/VHDL_Spectrogram/VHDL_Spectrogram.srcs/sources_1/ip/fft_ip/fft_ip.xci
# IP: The module: 'fft_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VHDL_Spectrogram/VHDL_Spectrogram.srcs/sources_1/ip/fft_ip/fft_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/VHDL_Spectrogram/VHDL_Spectrogram.srcs/sources_1/ip/fft_ip/fft_ip.xci
# IP: The module: 'fft_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/VHDL_Spectrogram/VHDL_Spectrogram.srcs/sources_1/ip/fft_ip/fft_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
