# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Ing/Master 1sem/Digitale/VHDL_Spectrogram/VHDL_Spectrogram.srcs/sources_1/ip/ROM_Static_img/ROM_Static_img.xci
# IP: The module: 'ROM_Static_img' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Ing/Master 1sem/Digitale/VHDL_Spectrogram/VHDL_Spectrogram.srcs/sources_1/ip/ROM_Static_img/ROM_Static_img_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_Static_img'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Ing/Master 1sem/Digitale/VHDL_Spectrogram/VHDL_Spectrogram.srcs/sources_1/ip/ROM_Static_img/ROM_Static_img.xci
# IP: The module: 'ROM_Static_img' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Ing/Master 1sem/Digitale/VHDL_Spectrogram/VHDL_Spectrogram.srcs/sources_1/ip/ROM_Static_img/ROM_Static_img_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_Static_img'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
