# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Ing/Master 1sem/Digitale/VHDL_Spectrogram/VHDL_Spectrogram.srcs/sources_1/ip/DUAL_PORT_RAM/DUAL_PORT_RAM.xci
# IP: The module: 'DUAL_PORT_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Ing/Master 1sem/Digitale/VHDL_Spectrogram/VHDL_Spectrogram.srcs/sources_1/ip/DUAL_PORT_RAM/DUAL_PORT_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DUAL_PORT_RAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Ing/Master 1sem/Digitale/VHDL_Spectrogram/VHDL_Spectrogram.srcs/sources_1/ip/DUAL_PORT_RAM/DUAL_PORT_RAM.xci
# IP: The module: 'DUAL_PORT_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Ing/Master 1sem/Digitale/VHDL_Spectrogram/VHDL_Spectrogram.srcs/sources_1/ip/DUAL_PORT_RAM/DUAL_PORT_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DUAL_PORT_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
